// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqDmsS1jBkw5Y4qqq7Clx11qX6D5ofGzI',
    appId: '1:24067715072:android:400ffe0e7d1d9bb33c68e5',
    messagingSenderId: '24067715072',
    projectId: 'vitalis-ai-d7e96',
    storageBucket: 'vitalis-ai-d7e96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWhT1RQXNvP73VwX4j7zJ3TYrBtxSi91M',
    appId: '1:24067715072:ios:b0afdd7f94b85a253c68e5',
    messagingSenderId: '24067715072',
    projectId: 'vitalis-ai-d7e96',
    storageBucket: 'vitalis-ai-d7e96.firebasestorage.app',
    iosClientId: '24067715072-2utd51q6vvdm2uq9ga291dtg22rds8f3.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodscanner.foodScanner',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsDSoFDOr2KwZu4ClEFqrMO7zA_NE6EQY',
    appId: '1:24067715072:web:688259d5057e2aab3c68e5',
    messagingSenderId: '24067715072',
    projectId: 'vitalis-ai-d7e96',
    authDomain: 'vitalis-ai-d7e96.firebaseapp.com',
    storageBucket: 'vitalis-ai-d7e96.firebasestorage.app',
    measurementId: 'G-FYYJN1L18K',
  );

}